baseURL: https://aadi-nair.github.io/portfolio/
languageCode: en-us
title: Aditya Nair
theme: PaperMod

params:
  # homeInfoParams:
  #   Title: Hi, I'm Aditya
  #   Content: "I'm a CS Grad at UIC"
  profileMode:
    enabled: true
    title: "Aditya Nair" # optional default will be site title
    subtitle: "CS Grad @UIC"
    # imageUrl: "https://avatars.githubusercontent.com/u/18663918?v=4" # optional
    imageUrl: "img/profile.png" # optional

    imageTitle: "" # optional
    # imageWidth: 250 # custom size
    # imageHeight: 240 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/aadi-nair"
    - name: linkedin
      url: "https://www.linkedin.com/in/aadi-nair/"
    - name: cv
      url: "resume/Aditya_Resume.pdf"
      # title: "Github"
      # url: "www.google.com"
menu:
  main:
    - identifier: experience
      name: Experience
      url: /experience
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
